### ISSUE TITLE
Name in the Graphic tab when showing results from multiple queries

### ISSUE THREAD

**Issue by gexijin** [pgdurand/BlastViewer#6]
Thank you for developing this tool. 
Really like it. I even tweeted about it.
https://twitter.com/StevenXGe/status/1145054748384681984

One minor thing I found is this. I have two queries. When I switch from to show results for query 1 to query 2, everything switches fine in the Hits tabs. However, one thing that is not changed is the Name and Size information on the Graphic tab. The ruler on the top doesn't seem updated either. 

Thanks.
Xijin

**Comment by pgdurand** [comment]
Hi Xijin,

I'm working on a major update of BlastViewer that should be available by September... I'll check the bug you mentionned and hopefully it should be fixed with that new release.

Thanks for sharing on Twitter ! ;-)

Patrick

**Comment by gexijin** [comment]
Dear Patrick,
I’ve been using it in the last few weeks. It is such a useful tool!
Graphical and intuitive.
Best,
Xijin

**Comment by pgdurand** [comment]
this issue should by fixed by now... try BlastViewer v5.3.0 released a few minutes ago today !
